version: '3.9'
services:
  app:
    build: .
    ports:
     - "80:5000"
    environment:
      NODE_PORT: 5000
  mongo:
    image: mongo
    volumes:
      - mongo:/usr/src/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongo: